/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by tools/experimental-validator. DO NOT EDIT.

package v1

import (
	"fmt"
	"k8s.io/apimachinery/pkg/runtime"
)

// validateExperimentalFields is a generic validation function that checks for experimental fields.
// It takes an object and a check function that returns the list of experimental fields found.
func validateExperimentalFields[T any](obj *T, checkFunc func(*T) []string) error {
	if obj == nil {
		return nil
	}

	experimentalFields := checkFunc(obj)

	if len(experimentalFields) > 0 {
		return fmt.Errorf("experimental fields in use: %v", experimentalFields)
	}
	return nil
}

// checkGRPCRouteFields returns a list of experimental fields found in GRPCRoute
func checkGRPCRouteFields(obj *GRPCRoute) []string {
	var experimentalFields []string

	// Check spec.useDefaultGateways
	if obj.Spec.UseDefaultGateways != "" { // Non-zero check
		experimentalFields = append(experimentalFields, "spec.useDefaultGateways")
	}

	// Check spec.rules.sessionPersistence
	for _, item0 := range obj.Spec.Rules {
		if item0.SessionPersistence != nil {
			experimentalFields = append(experimentalFields, "spec.rules.sessionPersistence")
			break // Only report once
		}
	}

	return experimentalFields
}

// ValidateGRPCRouteExperimentalFields checks for experimental fields in GRPCRoute.
// Returns an error listing all experimental fields that are in use, or nil if no experimental fields are used.
func ValidateGRPCRouteExperimentalFields(obj *GRPCRoute) error {
	return validateExperimentalFields(obj, checkGRPCRouteFields)
}

// checkGatewayFields returns a list of experimental fields found in Gateway
func checkGatewayFields(obj *Gateway) []string {
	var experimentalFields []string

	// Check spec.allowedListeners
	if obj.Spec.AllowedListeners != nil {
		experimentalFields = append(experimentalFields, "spec.allowedListeners")
	}

	// Check spec.tls
	if obj.Spec.TLS != nil {
		experimentalFields = append(experimentalFields, "spec.tls")
	}

	// Check spec.tls.backend
	if obj.Spec.TLS != nil && obj.Spec.TLS.Backend != nil {
		experimentalFields = append(experimentalFields, "spec.tls.backend")
	}

	// Check spec.tls.backend.clientCertificateRef
	if obj.Spec.TLS != nil && obj.Spec.TLS.Backend != nil && obj.Spec.TLS.Backend.ClientCertificateRef != nil {
		experimentalFields = append(experimentalFields, "spec.tls.backend.clientCertificateRef")
	}

	// Check spec.tls.frontend
	if obj.Spec.TLS != nil && obj.Spec.TLS.Frontend != nil {
		experimentalFields = append(experimentalFields, "spec.tls.frontend")
	}

	// Check spec.tls.frontend.default.validation
	if obj.Spec.TLS != nil && obj.Spec.TLS.Frontend != nil && obj.Spec.TLS.Frontend.Default.Validation != nil {
		experimentalFields = append(experimentalFields, "spec.tls.frontend.default.validation")
	}

	// Check spec.tls.frontend.perPort.tls.validation
	if obj.Spec.TLS != nil && obj.Spec.TLS.Frontend != nil {
		for _, item0 := range obj.Spec.TLS.Frontend.PerPort {
			if item0.TLS.Validation != nil {
				experimentalFields = append(experimentalFields, "spec.tls.frontend.perPort.tls.validation")
				break // Only report once
			}
		}
	}

	// Check spec.defaultScope
	if obj.Spec.DefaultScope != "" { // Non-zero check
		experimentalFields = append(experimentalFields, "spec.defaultScope")
	}

	return experimentalFields
}

// ValidateGatewayExperimentalFields checks for experimental fields in Gateway.
// Returns an error listing all experimental fields that are in use, or nil if no experimental fields are used.
func ValidateGatewayExperimentalFields(obj *Gateway) error {
	return validateExperimentalFields(obj, checkGatewayFields)
}

// checkHTTPRouteFields returns a list of experimental fields found in HTTPRoute
func checkHTTPRouteFields(obj *HTTPRoute) []string {
	var experimentalFields []string

	// Check spec.useDefaultGateways
	if obj.Spec.UseDefaultGateways != "" { // Non-zero check
		experimentalFields = append(experimentalFields, "spec.useDefaultGateways")
	}

	// Check spec.rules.filters.cors
	for _, item0 := range obj.Spec.Rules {
		for _, item1 := range item0.Filters {
			if item1.CORS != nil {
				experimentalFields = append(experimentalFields, "spec.rules.filters.cors")
				break // Only report once
			}
		}
	}

	// Check spec.rules.filters.externalAuth
	for _, item0 := range obj.Spec.Rules {
		for _, item1 := range item0.Filters {
			if item1.ExternalAuth != nil {
				experimentalFields = append(experimentalFields, "spec.rules.filters.externalAuth")
				break // Only report once
			}
		}
	}

	// Check spec.rules.backendRefs.filters.cors
	for _, item0 := range obj.Spec.Rules {
		for _, item1 := range item0.BackendRefs {
			for _, item2 := range item1.Filters {
				if item2.ExtensionRef != nil {
					experimentalFields = append(experimentalFields, "spec.rules.backendRefs.filters.cors")
					break // Only report once
				}
			}
		}
	}

	// Check spec.rules.backendRefs.filters.externalAuth
	for _, item0 := range obj.Spec.Rules {
		for _, item1 := range item0.BackendRefs {
			for _, item2 := range item1.Filters {
				if item2.ExtensionRef != nil {
					experimentalFields = append(experimentalFields, "spec.rules.backendRefs.filters.externalAuth")
					break // Only report once
				}
			}
		}
	}

	// Check spec.rules.retry
	for _, item0 := range obj.Spec.Rules {
		if item0.Retry != nil {
			experimentalFields = append(experimentalFields, "spec.rules.retry")
			break // Only report once
		}
	}

	// Check spec.rules.sessionPersistence
	for _, item0 := range obj.Spec.Rules {
		if item0.SessionPersistence != nil {
			experimentalFields = append(experimentalFields, "spec.rules.sessionPersistence")
			break // Only report once
		}
	}

	return experimentalFields
}

// ValidateHTTPRouteExperimentalFields checks for experimental fields in HTTPRoute.
// Returns an error listing all experimental fields that are in use, or nil if no experimental fields are used.
func ValidateHTTPRouteExperimentalFields(obj *HTTPRoute) error {
	return validateExperimentalFields(obj, checkHTTPRouteFields)
}


// HasExperimentalFields checks if the given Gateway API object uses any experimental fields.
// Returns an error listing all experimental fields that are in use, or nil if no experimental fields are used.
//
// This function only validates objects marked with +kubebuilder:object:root=true.
// Only the Spec field is validated; Status and Metadata are not checked.
func HasExperimentalFields(obj runtime.Object) error {
	switch v := obj.(type) {
	case *GRPCRoute:
		return ValidateGRPCRouteExperimentalFields(v)
	case *Gateway:
		return ValidateGatewayExperimentalFields(v)
	case *HTTPRoute:
		return ValidateHTTPRouteExperimentalFields(v)
	default:
		return fmt.Errorf("unknown type: %T", obj)
	}
}
